services:
  navidrome:
    image: "deluan/navidrome:0.63.2"
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - "data:/data"
      - "/srv/navidrome/music:/music"
      - "./data/navidrome.toml:/data/navidrome.toml"
    environment:
      - "ND_LASTFM_APIKEY=${ND_LASTFM_APIKEY}"
      - "ND_LASTFM_SECRET=${ND_LASTFM_SECRET}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.music.entryPoints=webSecure"
      - "traefik.http.routers.music.rule=Host(`music.ocd.beauty`)"
      - "traefik.http.services.music.loadBalancer.server.port=4533"

networks:
  proxy:
    external: true

volumes:
  data:
