# SPDX-FileCopyrightText: 2026 Nuptials5178 <nuptials5178@ocd.beauty>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
services:
  beszel:
    image: 'henrygd/beszel:0.18.8'
    restart: unless-stopped
    volumes:
      - 'beszel-data:/beszel_data'
      - 'beszel-socket:/beszel_socket'
    ports:
      - '127.0.0.1:8090:8090'
    environment:
      - 'APP_URL=http://localhost:8090'

  beszel-agent:
    image: 'henrygd/beszel-agent:0.18.8'
    restart: unless-stopped
    volumes:
      - 'beszel-socket:/beszel_socket'
      - 'var-lib-beszel-agent:/var/lib/beszel-agent'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - 'HUB_URL=http://beszel:8090'
      - 'KEY=${KEY}'
      - 'LISTEN=/beszel_socket/beszel.sock'
      - 'TOKEN=${TOKEN}'
    depends_on:
      - beszel

volumes:
  beszel-agent-data:
  beszel-socket:
  var-lib-beszel-agent:
