# SPDX-FileCopyrightText: 2026 Nuptials5178 <nuptials5178@ocd.beauty>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
endpoints:
  - name: Forgejo
    url: https://git.ocd.beauty
    conditions:
      - '[STATUS] == 200'

  - name: Navidrome
    url: https://music.ocd.beauty
    conditions:
      - '[STATUS] == 200'

  - name: Woodpecker CI
    url: https://ci.ocd.beauty
    conditions:
      - '[STATUS] == 200'

ui:
  custom-css: |
    @font-face {
      font-family: 'JetBrains Mono';
      src: url('https://cdn.jsdelivr.net/fontsource/fonts/jetbrains-mono@latest/latin-400-normal.woff2') format('woff2');
    }
    body, * {
      font-family: 'JetBrains Mono', monospace !important;
    }

storage:
  type: sqlite
  path: /data/data.db
