services:
  gatus:
    container_name: "gatus"
    image: "twinproduction/gatus:v5.36.0"
    restart: unless-stopped
    volumes:
      - "data:/data"
      - "./config/config.yaml:/config/config.yaml"
    ports:
      - "127.0.0.1:8081:8080"

volumes:
  data:
