# SPDX-FileCopyrightText: 2026 Nuptials5178 <nuptials5178@ocd.beauty>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
services:
  gatus:
    image: 'twinproduction/gatus:v5.36.0'
    restart: unless-stopped
    networks:
      - proxy
    volumes:
      - 'data:/data'
      - './config/config.yaml:/config/config.yaml'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.status.entryPoints=webSecure'
      - 'traefik.http.routers.status.rule=Host(`status.ocd.beauty`)'
      - 'traefik.http.services.status.loadBalancer.server.port=8080'

networks:
  proxy:
    external: true

volumes:
  data:
